### ISSUE TITLE
Barrels need pickaxes to break

### ISSUE THREAD

**Issue by goldenapple3** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#25]
It looks like I can't harvest wood barrels with an axe - I need a pickaxe instead. In the BlockBarrelTweak class I saw this:
```
public BlockBarrelTweak() {
    super(Material.rock);
```
So I'm assuming you chose the wrong material (it should be wood).

I'm using version 1.01-18, in case you are wondering.

**Comment by LoveHoly** [comment]
Fix that, Thks!
