### ISSUE TITLE
NPE when summoning coven witch

### ISSUE THREAD

**Issue by Timeslice42** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#28]
When I throw a witches hand in a barrel of witch water I get the following error: http://paste.ee/d/37MTs

Is this because I haven't yet replaced the ex nihilo barrel with the EAR barrel?
Update: I get this same error if I use the EAR barrel: http://paste.ee/d/aMq07

**Comment by LoveHoly** [comment]
hm... this error is not ex astris rebirth error... ex nihilo...

**Comment by Timeslice42** [comment]
My bad, I'll make a ticket on Mike's bitbucket.
