### ISSUE TITLE
Bad copy/paste in config file

### ISSUE THREAD

**Issue by Timeslice42** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#29]
The following is an excerpt from the generated config file:
```
tinkersconstruct {
    # Enable Mini Smeltery
    B:hardStone=true

    # Add Tinkers Modifiers (Smashing and Crooked
    B:modifiers=true
```

"Enable Mini Smeltery" should be something other than "B:hardStone=true"; that's the option for the rotarycraft bedrock.

**Comment by LoveHoly** [comment]
oh i mistake..

**Comment by LoveHoly** [comment]
Fixed .
