### ISSUE TITLE
Barrels consume buckets when filling with water

### ISSUE THREAD

**Issue by Nova001Sol** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#31]
Whenever I right-click an oak barrel with a water bucket, the bucket vanishes.

**Comment by LoveHoly** [comment]
Please note detail..

**Comment by Nova001Sol** [comment]
What do you mean? There's not much else to say about it. I place an oak barrel, right-click it with a bucket of water, the oak barrel fills with water but does not return an empty bucket. I'm using Ex Astris Rebirth 1.01-21.

**Comment by LoveHoly** [comment]
I made Barrels extends an ExNihilo Barrel.

Perhaps it's exnihilo bug.

**Comment by Nova001Sol** [comment]
Wow, I thought this was closed weeks ago. It appears I was mistaken. Anyway, I figured out the issue, and it lies with CoFHCore, not Ex Astris. So I think I'll close this now.
