### ISSUE TITLE
[Suggestion] IC2 Energy Network Support (for auto sieve/hammer)

### ISSUE THREAD

**Issue by hephinator** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#34]
Currently, Ex Astris has the Auto-Sieve and Auto-Hammer, which use the CoFH RF energy network.

I am working on an IC2/GregTech based SkyBlock modpack which would benefit greatly from the automation provided in the auto-sieve/auto-hammer.

Would it be possible to add IC2 energy support (and a config option to disable either RF or IC2 energy networks)? I feel like this would help with modpack devs overall.

Thanks!

**Comment by abculatter2** [comment]
I'm just going to second this, and I would also add that it would be nice to have some form of electric tool-hammer, to compliment the RF hammer.

**Comment by roboliutas** [comment]
Its possible, but ic2 is...a bit of a forgotten mod these days even though it seems that immersive engineering has a way to turn rf into eu, so why not try that?

**Comment by hephinator** [comment]
Going to close this issue. @MozeIntel is going to fork this repo and submit a pull request with not only IC2 support, but also GT energy networks for the auto sieve and hammer.
