### ISSUE TITLE
Crash with TiC & TSteelworks

### ISSUE THREAD

**Issue by InkDragon** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#36]
Crash for just Tinkers Construct: http://pastebin.com/9m3Xe1fp

Crash With Tinkers Construct + Steelworks: http://pastebin.com/ZTfRWDgm

Submitting both because they show different errors

**Comment by LoveHoly** [comment]
Can you down-grade Java 1.7?

**Comment by InkDragon** [comment]
Still crashes with java 7
http://pastebin.com/EqpEN3ZC

**Comment by LoveHoly** [comment]
can you down-grade forge 10.13.3.1408-1.7.10?

hm...

**Comment by InkDragon** [comment]
http://pastebin.com/pf8SLLSn

I don't believe it is an issue with my java or forge as I receive this issue with the latest Ex Astris from curse:

http://pastebin.com/aJ87fAXw

**Comment by LoveHoly** [comment]
Install Thermal Expansion, Foundation, COFHCORE
perhaps solve a problem...

**Comment by InkDragon** [comment]
http://pastebin.com/CUtcm9vv

Still crashing with the latest(alpha releases) from curse of CoFH Core, Thermal Foundation and Thermal Expansion.

However the crash looks more like the one I get from ex astris, could this be because I am using the last stable build(1.0.7) rather than the latest alpha builds(1.1.0-16)?

**Comment by LoveHoly** [comment]
tinker's steelworks update

https://github.com/Ephys/TinkersSteelworks/releases

**Comment by InkDragon** [comment]
1.1.0-6 is not a stable release and causes crashes(100% a tsteelworks thing fixed in later alpha builds).
1.1.0-16 produces this crash with ex astris rebirth, http://pastebin.com/uD64tz5u

**Comment by LoveHoly** [comment]
fix that

**Comment by InkDragon** [comment]
So it'll be fixed in the next release?

**Comment by LoveHoly** [comment]
be in the process of compiling

**Comment by InkDragon** [comment]
Alright Thanks! I'll let you know if I find any more bugs
