### ISSUE TITLE
Crash on Startup - Ars Magica 2 - BarrelRecipeRegistry.addFluidTransformRecipe

### ISSUE THREAD

**Issue by DerOli82** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#40]
Crash-Report: http://pastebin.com/jfMf317W

Forge:
10.13.3.1408 and 10.13.3.1428

Only these four Mods:
- animationapi-1.7.10-1.2.4.jar
- arsmagica2-1.7.10-1.4.0.008.jar
- ex-astris-rebirth-1.7.10-1.01-42.jar
- ex-nihilo-1.7.10-1.38-36.jar

Same problem with "arsmagica2liquidEssence=false"

**Comment by LoveHoly** [comment]
http://minecraft.curseforge.com/mc-mods/221696-ex-nihilo/files 

Update ex nihilo

**Comment by DerOli82** [comment]
Sorry my fault. I've updated all mods except ex nihilo :-S Works fine with the latest version.
