### ISSUE TITLE
Crash upon using NEI to check recipes (1.01-42)

### ISSUE THREAD

**Issue by iExalt** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#41]
When using NEI to check what can be crafted with a certain item, Minecraft crashes. (Pressing U in NEI, not R)
I have confirmed that the crash happens with sand and gravel. I believe all siftable blocks have this problem as well.
The products from the sieve work perfectly though; I can see the "usage" of broken silver ore fine.
[Crash report](http://pastebin.com/eSpPAb1N)

**Comment by LoveHoly** [comment]
private paste;;;

**Comment by iExalt** [comment]
my bad
[this should be better](http://pastebin.com/0eRs9Nf8)

**Comment by iExalt** [comment]
I believe it is an NEI issue, not an Ex Astris issue. I just fixed it by updating my NEI.
