### ISSUE TITLE
Unable to crate dev workspace

### ISSUE THREAD

**Issue by MikeLydeamore** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#44]
I think a file moved off of your server and the build.gradle wasn't updated:

A problem occurred evaluating root project 'Ex-Astris-Rebirth'.
> http://loveholy.kr/libs/FoodPlus-1.7.2-3.2rS.jar

The /libs/ directory doesn't seem to exist anymore.

**Comment by LoveHoly** [comment]
sorry.. i mistake, fix that.
