### ISSUE TITLE
Auto Sieve / Hammer

### ISSUE THREAD

**Issue by Mattabase** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#51]
Neither one shows up for me in NEI or the Creative menu.

**Comment by ceiphas** [comment]
if (Loader.isModLoaded("ThermalExpansion"))
    {
        blockSieveAutomatic = ModThermalExpansion.blockSieveAutomatic();
        GameRegistry.registerBlock(blockSieveAutomatic, ItemBlockSieveAutomatic.class ,ExAstrisRebirthData.SIEVE_AUTOMATIC);

        blockHammerAutomatic = ModThermalExpansion.blockHammerAutomatic();
        GameRegistry.registerBlock(blockHammerAutomatic, ExAstrisRebirthData.HAMMER_AUTOMATIC);
    }

If i read this code right, these machines only work when Thermal expansion is installed, but i found no valid cause why thermal expansion is needed... any mod using the cofh api would suffice

**Comment by pjfranke** [comment]
They use Invar and Electrum for their construction, which are Thermal Expansion materials, as well as Pyrotheum for the speed upgrade IIRC.  Without TE, you can't make any of that.

**Comment by SirWilli** [comment]
Would be great if they are useable without ThermalExpansion

**Comment by technolem** [comment]
You can use those without thermal expansion, you just need thermal foundation + something to merge liquids like Tcon smelteries. Now, why you would have thermal foundation but not thermal expansion is another question.

**Comment by Mattabase** [comment]
Alright thanks, I shall do that. It is a pack using buildcraft as the main mod so I do not want TE but I can add TF to get them to load.

**Comment by technolem** [comment]
Oh well, I meant that in theory they could work if the mod checked for foundation instead of expansion. It doesn't, so it won't.

**Comment by SirWilli** [comment]
I don't undestand why this check is not for the recipe instead of the item. So modpack authors can add a custom recipe.

**Comment by Mattabase** [comment]
Yeah, I would love the block to show up. I have BC so I have power for them. Just missing the mods your are looking for.

**Comment by Sir-Will** [comment]
When will be this version released?
