### ISSUE TITLE
Crash at Startup using 1.01-45 [forge 1490]

### ISSUE THREAD

**Issue by ate0ate** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#53]
After "updating" from Ex Astris 1.16-36 to Ex Astris Rebirth 1.01-45 I now get this crash at startup...

http://pastebin.com/2rYPZKX8

I am guessing it is due to Thaumcraft aspects being added by the Forbidden Magic addon, but I have no clue if I am right. Reverting back to ExAstris 1.16-36 solves the crash for now. Thank you for your time.

**Comment by apotheoseGrifter** [comment]
I got this same exact error. Some testing revealed that the problem is likely some sort of conflict between Ex Astris and Witching Gadgets, since the modpack works perfectly fine if I remove either of them.

Crash report for reference: http://pastebin.com/RbV1Z9zk

**Comment by ate0ate** [comment]
Wow, I guess this is fixed by now?
