### ISSUE TITLE
Crash when summoning blaze, see below log.

### ISSUE THREAD

**Issue by Aelar-Nailo** [Ex-Astris-Rebirth/Ex-Astris-Rebirth#74]

**Comment by Aelar-Nailo** [comment]
Important note, the barrel was located in a three block hole, and the crash occured when I removed a block touching the barrel. Please respond quickly, as the world is currently unplayable.

**Comment by dajaco81** [comment]
Obviously way to late now but for anyone else: you need to remove the barrel in mcEdit to fix the issue. This crash has happened numerous times to me and is a massive inconvenience

**Comment by Aelar-Nailo** [comment]
> Obviously way to late now but for anyone else: you need to remove the barrel in mcEdit to fix the issue. This crash has happened numerous times to me and is a massive inconvenience

Holy crap man.
I don't even remember reporting this, or playing this modpack.
Ironic that I asked for a rapid response, but thanks for the assist!

**Comment by Aelar-Nailo** [comment]
Also I guess I should close this? Because it's not going to get fixed.
